// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFXji0tc6nLJfv-NFcuKod-IHU-5jTZX8',
    appId: '1:578289339512:web:079eab3e0cca5dc31ff18d',
    messagingSenderId: '578289339512',
    projectId: 'esp32-firebase-demo-f2551',
    authDomain: 'esp32-firebase-demo-f2551.firebaseapp.com',
    databaseURL: 'https://esp32-firebase-demo-f2551-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-demo-f2551.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBII78wJW9-Kjv5f6kuIPeyiWx__ZGWzRY',
    appId: '1:578289339512:android:ce1f7252a5dc0c491ff18d',
    messagingSenderId: '578289339512',
    projectId: 'esp32-firebase-demo-f2551',
    databaseURL: 'https://esp32-firebase-demo-f2551-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-demo-f2551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJipH10Ecm9LRkSp8cfL6alL1SbFRVnQ',
    appId: '1:578289339512:ios:dde2082fb858cefa1ff18d',
    messagingSenderId: '578289339512',
    projectId: 'esp32-firebase-demo-f2551',
    databaseURL: 'https://esp32-firebase-demo-f2551-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-demo-f2551.appspot.com',
    iosClientId: '578289339512-hud217mher1jcnm1a3ml3frlbc1o4c2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sibiruDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJipH10Ecm9LRkSp8cfL6alL1SbFRVnQ',
    appId: '1:578289339512:ios:dd7f519bf79d1eea1ff18d',
    messagingSenderId: '578289339512',
    projectId: 'esp32-firebase-demo-f2551',
    databaseURL: 'https://esp32-firebase-demo-f2551-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'esp32-firebase-demo-f2551.appspot.com',
    iosClientId: '578289339512-pbi1tbcmurbpf6am33nkd4ulvko8v9ee.apps.googleusercontent.com',
    iosBundleId: 'com.example.sibiruDriver.RunnerTests',
  );
}
